"""up

迁移 ID: 11806f37b8ea
父迁移:
创建时间: 2025-05-22 16:12:44.786649
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "11806f37b8ea"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ("lgc_nb_additions",)
depends_on: str | Sequence[str] | None = "f1c5ad2542ee"


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lgc_req_forward_request_info", schema=None) as batch_op:
        batch_op.add_column(sa.Column("modified_at", sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lgc_req_forward_request_info", schema=None) as batch_op:
        batch_op.drop_column("modified_at")

    # ### end Alembic commands ###
