"""up

迁移 ID: b1cac37e9a7b
父迁移: f1c5ad2542ee
创建时间: 2025-05-22 20:43:13.387788

"""

from __future__ import annotations

from collections.abc import Sequence
from datetime import UTC, datetime

import sqlalchemy as sa
from alembic import op

revision: str = "b1cac37e9a7b"
down_revision: str | Sequence[str] | None = "f1c5ad2542ee"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = "f1c5ad2542ee"


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lgc_req_forward_request_info", schema=None) as batch_op:
        batch_op.add_column(sa.Column("modified_at", sa.Float(), nullable=True))
    with op.batch_alter_table("lgc_req_forward_request_info", schema=None) as batch_op:
        batch_op.execute(
            f"UPDATE lgc_req_forward_request_info"  # noqa: S608
            f" SET modified_at = {datetime.now(UTC).timestamp()}",
        )
        batch_op.alter_column("modified_at", nullable=False)
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lgc_req_forward_request_info", schema=None) as batch_op:
        batch_op.drop_column("modified_at")
    # ### end Alembic commands ###
