"""init

迁移 ID: f1c5ad2542ee
父迁移:
创建时间: 2025-05-12 12:36:02.687409
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f1c5ad2542ee"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lgc_req_forward_request_info",
        sa.Column("id", sa.String(length=8), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "CONFIRMED", name="requeststatus"),
            nullable=False,
        ),
        sa.Column(
            "type",
            sa.Enum("FRIEND", "GUILD_INVITE", name="requesttype"),
            nullable=False,
        ),
        sa.Column("bot_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("identifier", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lgc_req_forward_request_info")),
        info={"bind_key": "req_forward"},
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("lgc_req_forward_request_info")
    # ### end Alembic commands ###
